"""empty message

Revision ID: 559ea277a4b6
Revises: ccfc14aaee5a
Create Date: 2024-08-13 00:32:13.422054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '559ea277a4b6'
down_revision = 'ccfc14aaee5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('salt', sa.String(length=180), nullable=False))
        batch_op.add_column(sa.Column('avatar', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('public_id_avatar', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('update_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('update_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('public_id_avatar')
        batch_op.drop_column('avatar')
        batch_op.drop_column('salt')
        batch_op.drop_column('lastname')

    # ### end Alembic commands ###
